# Nixpacks configuration for Track Management System Backend
# This ensures Chromium is installed for PDF generation via Puppeteer

[phases.setup]
# Install Chromium and required dependencies for PDF generation
# Note: Using t64 variants for Ubuntu Noble (24.04) compatibility
aptPkgs = [
  "chromium",
  "chromium-driver",
  "fonts-liberation",
  "libappindicator3-1",
  "libasound2t64",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libcups2t64",
  "libdbus-1-3",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0t64",
  "libnspr4",
  "libnss3",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxkbcommon0",
  "libxrandr2",
  "xdg-utils",
  "fonts-noto",
  "fonts-noto-color-emoji",
  "curl",
  "wget"
]

[phases.install]
# Set Puppeteer to use system Chromium
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:pm2"

[variables]
# Tell Puppeteer to skip downloading Chromium and use system installation
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
NODE_ENV = "production"
